trigger:
  batch: true
  branches:
    include:
    - master

pool:
  vmImage: 'ubuntu-latest'

workingDirectory: ./src

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '*.csproj'
    workingDirectory: 'src'
