trigger:
  batch: true
  branches:
    include:
    - master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
    - task: DotNetCoreCLI@2
      name: build
      inputs:
        command: 'build'
        projects: '**/*.csproj'

    - task: DotNetCoreCLI@2
      name: test
      inputs:
        command: 'test'
        projects: '**/*.Tests.Unit.csproj'
- stage: Deploy_Prod
  jobs:
    - job: DeployNuget
      steps:
        - task: GitVersion@5
          inputs:
            runtime: 'core'
            updateAssemblyInfo: true
        - task: DotNetCoreCLI@2
          name: pack
          inputs:
            command: 'pack'
            packagesToPack: '**/*.csproj'
            nobuild: true
            includesymbols: true
            includesource: true
            versioningScheme: 'byBuildNumber'
        - task: NuGetCommand@2
          inputs:
            command: 'push'
            packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
            nuGetFeedType: 'external'
            publishFeedCredentials: 'Nuget'